export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as Contact} from "./Contact"
export {default as AddContact} from "./AddContact"
export {default as EditContact} from "./EditContact"